name: Compilar dylib DOMIDIOS
on:
  push:
    branches:
      - main
  workflow_dispatch: # Esto permite darle al botón "Play" para compilar manual

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Theos
        run: |
         name: Compilar dylib DOMIDIOS
on:
  push:
    branches:
      - main
  workflow_dispatch: # Esto permite darle al botón "Play" para compilar manual

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Compilar dylib
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Guardar dylib (Artifacts)
        uses: actions/upload-artifact@v3
        with:
          name: DominioFlex-Dylib
          path: .theos/obj/debug/*.dylib
      - name: Compilar dylib
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Guardar dylib (Artifacts)
        uses: actions/upload-artifact@v3
        with:
          name: DominioFlex-Dylib
          path: .theos/obj/debug/*.dylib
