Package: com.domidios.flex
Name: DominioFlex
Depends: mobilesubstrate
Version: 1.0
Architecture: iphoneos-arm
Description: VIP Patches by iOS DOMIDIOS
Maintainer: DOMIDIOS
Author: DOMIDIOS
Section: Tweaks
